name: Build, Push & Deploy

on:
  push:
    branches: [main]

jobs:
  ci-check:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: enable corepack (pnpm)
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  build-and-push:
    name: build and push docker image
    runs-on: ubuntu-latest
    needs: ci-check
    if: github.ref == 'refs/heads/main'

    steps:
      - name: checkout code from the default
        uses: actions/checkout@v4

      - name: log in to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.docker_username }}/${{ secrets.package_name }}:latest

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: copy compose file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.vps_host }}
          username: ${{ secrets.vps_user }}
          key: ${{ secrets.vps_ssh_private_key }}
          source: 'compose.yml'
          target: '~/app'

      - name: copy caddy file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.vps_host }}
          username: ${{ secrets.vps_user }}
          key: ${{ secrets.vps_ssh_private_key }}
          source: 'caddyfile'
          target: '~/app'

      - name: deploy via ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.vps_host }}
          username: ${{ secrets.vps_user }}
          key: ${{ secrets.vps_ssh_private_key }}
          script: |
            cd ~/app
            # pull the latest images
            docker compose pull

            # stop and remove existing containers safely
            docker compose down --remove-orphans

            # start containers in detached mode
            docker compose up -d

            # Prune unused Docker objects (optional, cleans disk)
            docker system prune -f
